### ISSUE TITLE
Error when there's a space in the path where this is used

### ISSUE THREAD

**Issue by bsharper** [emarref/webicon#4]
Thanks for this script! It's really useful. I had one small issue because the path I am using it in has a space in it. The fix is to quote the variables used for paths. Here's a diff to save you some time:
http://pastebin.com/kV1cXnKU

I also added OptiPNG to squeeze the files down a bit more: http://pastebin.com/TXjCGYGr

Thanks again!

**Comment by emarref** [comment]
Awesome, thanks! Those are very useful changes. I see you've made your changes on a fork. If you create a couple of pull requests back to my repository (one for the filenames and one for the optiPNG), I can merge it straight in without needing the patch.

**Comment by emarref** [comment]
Bump

**Comment by bsharper** [comment]
@emarref Sorry for the very long delay, I'm not very experienced with pull requests. I have everything in a local branch (both as one commit unfortunately, let me know if I should do another branch with multiple). I'll try to get the pull request posted today.

**Comment by bsharper** [comment]
@emarref You should see the pull request now. Thanks for the reminder!

**Comment by emarref** [comment]
Fixed by #6
